export { default as Navbar } from './Navbar'
export { default as SideSocialIcons } from './SideSocialIcons'
export { default as Signin } from './Signin'
export { default as MainTextnImage } from './landingPage/MainTextnImage'
export { default as Footer } from './landingPage/Footer'
export { default as MainServices } from './landingPage/MainServices'